# Page settings

baseURL = "https://YiChunHung.github.io/"
languageCode = "en"
title = "Yi-Chun's Page"
theme = "hugo-devresume-theme"
#googleAnalytics = "UA-XXXXXXX-Y"
canonifyurls = true

[params]
    author = "Yi-Chun Hung"
    description = ""

    #primaryColor = '#292929'
    primaryColor = "#93827F"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Yi-Chun Hung"
        tagline = "Researcher"
        avatar = "avatar.jpg"

    [params.contact]
        enable = true
        location = "Chiayi City, Taiwan"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+886-3-5715131#34923"
        
	[[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "nick831111@gmail.com"
        
#	[[params.contact.list]]
#        icon = "fas fa-globe"
#        url = "#"
#        text = "www.yourwebsite.com"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/React"
        [[params.skills.list.items]]
        details = "Python/PHP"
        [[params.skills.list.items]]
        details = "MySQL"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"


    [params.education]
        enable = true

        
        [[params.education.list]]
        degree = "BSc Electrical Engineering (Major)"
        university = "National Tsing-Hua University"
        dates = "2014 - 2019"
	
	[[params.education.list]]
        degree = "BSc Mathematics (Minor)"
        university = "National Tsing-Hua University"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "PyTorch Scholarship Challenge from Facebook"
        body = "Awared a series of online courses relative to deep learning, which value hundrens of USD"
        date = "2018"
        [[params.awards.list]]
        name = "National Science Council Research Scholarship, Taiwan"
        body = "Conducted the research on 3D THz images for capsule quality control"
        date = "2018"
	[[params.awards.list]]
        name = "IEEE Arctic Chanllenge Sponsership"
        body = "The proposal, Arctic area pollution broadcast system, won over 5k USD"
        date = "2018"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "🏃🏽‍♂️ Jogging"
        [[params.interests.list]]
        name = "🎾 Tennis"
        [[params.interests.list]]
        name = "🏈 Football"
        [[params.interests.list]]
        name = "🎒 Travelling"

    [params.summary]
        enable = true
        text = "Mr. Yi-Chun Hung is currently a research assistant with professor Shang-Hua Yang in department of electrical engineering at National Tsing Hua University. He received his B.S. degree in electrical engineering from National Tsing Hua University, Taiwan, in 2019. Mr. Hung has conducted multiple interdisciplinary projects including non-destructive imaging, remote sensing and deep learning. The outcomes of his research were published into several international proceeding conference papers. Additionally, several patents and top-tier peer-reviewed journals are preparing on these research topics. He has also receive several international awards and scholarships including  PyTorch Scholarship Challenge from Facebook (2018), National Science Council Research Scholarship, Taiwan (2018) and IEEE Arctic Chanllenge Sponsership (2018, only 6 winners over the world). On the other hand, he is also an action-oriented educator to inspire his juniors to realize the creative ideas. To this end, he launched a semester-long cultivating program in 2017 to encourage juniors for the original and innovative projects. The program benefited over 50 juniors and been officially supported by the department. The program have kept running by juniors over 3 years."


    [params.researches]
        enable = true

        [[params.researches.list]]
        title = "Terahertz Deep Learning Computed Tomography"
        dates = "Oct 2018 - Present"
        details = ""
        [[params.researches.list.items]]
        details = "Designed the first supervised deep learning model based on terahertz time domain spectroscopy (THz-TDS) system to achieve the image resolution closed to diffraction limit."
        [[params.researches.list.items]]
        details = "Established the precise THz-TDS dataset, containing over 600 gigabytes raw signal data."
        [[params.researches.list.items]]
        details = "Utilized distributed computing system with automated hyperparameter tunning tool to improve the training efficiency."

        [[params.researches.list]]
        title = "Terahertz Compressed Sensing Imaging"
        dates = "May 2019 - Present"
        details = ""
        [[params.researches.list.items]]
        details = "Built the terahertz compressed sensing optical system by a 532nm laser on a spatial light modulator."
        [[params.researches.list.items]]
        details = "Implemented optimization based reconstruction algorithms, such as Hadamard matrix with Lasso."
        [[params.researches.list.items]]
        details = "Collaborating with the professor in polymer material design to improve the modulation efficiency."

	[[params.researches.list]]
        title = "Terahertz Hyperspectral Imaging"
        dates = "Sep 2019 - Present"
        details = ""

        [[params.researches.list.items]]
        details = "Formulated a terahertz data model for blind spectral unmixing algorithms."
        [[params.researches.list.items]]
        details = "Designed the precise experiments to validate the assumptions in the formulated model."
        [[params.researches.list.items]]
        details = "Collaborating with the professor in the optimization field to design the imaging reconstruction algorithm."




    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Terahertz Deep Learning Computed Tomography"
        dates = "Oct 2018 - Present"
        company = "National Tsing-Hua University - YRG Lab"
        details = ""
        [[params.experience.list.items]]
        details = "Designed the first supervised deep learning model based on terahertz time domain spectroscopy (THz-TDS) system to achieve the image resolution closed to diffraction limit."
        [[params.experience.list.items]]
        details = "Established the precise THz-TDS dataset, containing over 600 gigabytes raw signal data."
        [[params.experience.list.items]]
        details = "Utilized distributed computing system with automated hyperparameter tunning tool to improve the training efficiency."

        [[params.experience.list]]
        title = "Terahertz Compressed Sensing Imaging"
        dates = "May 2019 - Present"
        company = "National Tsing-Hua University - YRG Lab"
        details = ""
        [[params.experience.list.items]]
        details = "Built the terahertz compressed sensing optical system by a 532nm laser on a spatial light modulator."
        [[params.experience.list.items]]
        details = "Implemented optimization based reconstruction algorithms, such as Hadamard matrix with Lasso."
        [[params.experience.list.items]]
        details = "Collaborating with the professor in polymer material design to improve the modulation efficiency."

	[[params.experience.list]]
        title = "Terahertz Hyperspectral Imaging"
        dates = "Sep 2019 - Present"
        company = "National Tsing-Hua University - YRG Lab"
        details = ""

        [[params.experience.list.items]]
        details = "Formulated a terahertz data model for blind spectral unmixing algorithms."
        [[params.experience.list.items]]
        details = "Designed the precise experiments to validate the assumptions in the formulated model."
        [[params.experience.list.items]]
        details = "Collaborating with the professor in the optimization field to design the imaging reconstruction algorithm."


    [params.publications]
        enable = true

        [[params.publications.list]]
        title = "[1] __**Y.-C. Hung**__, S.-H. Yang, “Terahertz Deep Learning Computed Tomography”, Proc. International Conference on Infrared, Millimeter, and Terahertz Waves, Paris, France (2019) – Oral Presentation"
        meta = ""
        tagline = ""

        [[params.publications.list]]
        title = "[2] __**Y.-C. Hung**__, S.-H. Yang, “Kernel Size Characterization for Deep Learning Terahertz Tomography”, Proc. International Conference on Infrared, Millimeter, and Terahertz Waves, Paris, France (2019) – Poster Presentation"
        meta = ""
        tagline = ""

        [[params.publications.list]]
        title = "[3] B.-Y. Wu, __**Y.-C. Hung**__, S.-H. Yang, “Plasmonic-Enhanced Terahertz Tomography System”, Proc. International Conference on Computational Electromagnetics, Singapore (2020)"
        meta = ""
        tagline = ""
	
	    [[params.publications.list]]
        title = "[4] K.T.Z Htun, B.-Y. Wu, __**Y.-C. Hung**__, S.-H. Yang, “Terahertz LASSO Compressed Sensing Tomography System”, Proc. SPIE Photonic Europe, Strasbourg, France (2020)"
        meta = ""
        tagline = ""

         [[params.publications.list]]
         title = "[5] __**Y.-C. Hung**__, C.-H. Lin, F.-Y. Wang, S.-H. Yang, “Penetrating Terahertz Hyperspectral Unmixing via Löwner-John Ellipsoid (THz HU-LJE): An Unsupervised Algorithm”, Proc.International Conference on Infrared, Millimeter, and Terahertz Waves, Buffalo, NY USA (2020) - Submitted"
         meta = ""
         tagline = ""

        [[params.publications.list]]
         title = "[6] Z.-H. Tu, __**Y.-C. Hung**__, S.-H. Yang, “Terahertz Deep Learning Super Resolution Imaging Training on Sinogram”, Proc.International Conference on Infrared, Millimeter, and Terahertz Waves, Buffalo, NY USA (2020) - Submitted"
         meta = ""
         tagline = ""


    [params.selectedprojs]
        enable = true

        [[params.selectedprojs.list]]
        title = "Material Parameters Extraction Among Terahertz Region"
        meta = "Sep 2019 - Present"
        [[params.selectedprojs.list.items]]
	details = "Implementing the optimization based algorithm to extract the refractive index and absortion coefficient of the materials based on the Terahertz time domain system."

        [[params.selectedprojs.list]]
        title = "Learning-Based Autopiloted Cart"
        meta = "Dec 2017"
        [[params.selectedprojs.list.items]]
	details = "Implemented lane following carts with object detection to avoid obstacles on Udoo Neo and K64F."

        [[params.selectedprojs.list]]
        title = "Interactive RPG Mobile Game iOS Application"
        meta = "Jan 2017 - Aug 2017"
        
        [[params.selectedprojs.list.items]]
	details = "Implemented an IOS application for over 100 freshman welcome camp, including utilizing google map API, restful API, and data synchronizing with the self-build server."
	
 
    [params.workexpr]
        enable = true

        [[params.workexpr.list]]
        title = "Research Assistant, Yang Research Group"
        dates = "Sep 2019 - Present"
        company = "Dept. EE, NTHU"
        details = ""
        [[params.workexpr.list.items]]
        details = "Leading 9 interdisciplinary projects relative to optics, numerical modeling, optimization, and solid physics."
        [[params.workexpr.list.items]]
        details = "Collaborating with professors from different fields, such as digital IC design, optimization, and polymer material."

        [[params.workexpr.list]]
        title = "Teaching Assistant, Embedded System Laboratory"
        dates = "Dec 2017 - July 2018"
        company = "Dept. EE, NTHU"
        details = ""
        [[params.workexpr.list.items]]
        details = "Organized the teaching material for image recongnition based on deep learning onto embedded platform."
        [[params.workexpr.list.items]]
        details = "Implemented the lane following control system for the embedded cart based on image processing."


#    [params.information]
#        enable = true
#        [[params.information.list]]
#        title = "Interests"
#        details = "Tennis, Jogging, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/YiChunHung"
        title = "YiChunHung"
#        [[params.social.list]]
#        icon = "fab fa-linkedin"
#        url = "//linkedin.com/in/username"
#        title = "username"
#        [[params.social.list]]
#        icon = "fab fa-twitter-square"
#        url = "//twitter.com/username"
#        title = "@username"

